# Generated by Django 4.2.27 on 2025-12-15 01:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\(\\d{2}\\)\\s?\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ultima_visita', models.DateField(blank=True, null=True, verbose_name='Última Visita')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('observacao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Item de Serviço',
                'verbose_name_plural': 'Itens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº OS')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('data_previsao', models.DateField(verbose_name='Previsão de Entrega')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Aprovação'), ('em_andamento', 'Em Andamento'), ('aguardando_pecas', 'Aguardando Peças'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aguardando', max_length=20, verbose_name='Status')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Final')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='oficina.cliente')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_entrada', '-numero_os'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Padrão')),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo em horas', null=True, verbose_name='Tempo Estimado (h)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('placa', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}-\\d{4}$|^[A-Z]{3}\\d[A-Z]\\d{2}$')], verbose_name='Placa')),
                ('cor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cor')),
                ('km_atual', models.IntegerField(blank=True, null=True, verbose_name='KM Atual')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='oficina.cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('metodo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto')], max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='oficina.ordemservico')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servicos',
            field=models.ManyToManyField(through='oficina.ItemServico', to='oficina.servico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='oficina.veiculo'),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.ordemservico'),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficina.servico'),
        ),
    ]
