# Generated by Django 4.2.27 on 2025-12-15 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficina', '0002_alter_cliente_cpf_cnpj_oficina_cliente_oficina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficinas', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
    ]
