# Generated by Django 4.2.27 on 2025-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_alter_cliente_cpf_cnpj_alter_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando Aprovação'), ('em_andamento', 'Em Andamento'), ('aguardando_pecas', 'Aguardando Peças'), ('concluida', 'Concluída'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='aguardando', max_length=20, verbose_name='Status'),
        ),
    ]
